import matplotlib
# cmap = matplotlib.cm.get_cmap('hsv')

def cmap(idx, total):
    c_default = ['#377eb8', '#ff7f00', '#4daf4a',
                 '#f781bf', '#a65628', '#984ea3',
                 '#999999', '#e41a1c', '#dede00']
    if idx < len(c_default):
        return c_default[idx]
    else:
        getc = matplotlib.cm.get_cmap('cool')
        return getc(float(idx - len(c_default))/(total- len(c_default)))


target_keywords = {
    "decorrelation.txt": "Decorrelation:",
    "distance.txt": "Distance",
    "noninterference.txt": "Noninterference:",
    "linear_probing_xy.txt": "Percentage error",
    "linear_probing_color.txt": "Percentage error",
    "linear_probing_count.txt": "Percentage error",
    "orthogonality.txt": "Orthogonality:",
    "sparsity_instance.txt": "sparsity:",
}
target_files = {
    "decorr": "decorrelation.txt",
    "distance": "distance.txt",
    "noninterf": "noninterference.txt",
    "ortho": "orthogonality.txt",
    "sparsity": "sparsity_instance.txt"
}

violin_colors = {
    "DQN": "C4",

    "DQN+XY": "C1",
    "DQN+XY+color": "goldenrod",
    "DQN+XY+count": "C8",
    "DQN+Decoder": "C3",
    "DQN+NAS": "C5",
    "DQN+SF": "C6",
    "DQN+AuxControl": "C0",
    "DQN+AuxControl1g": "C0",
    "DQN+AuxControl5g": "C9",
    "DQN+Reward": "C10",

    "DQN+LTA": "C2",
    "DQN+LTA(no target)": "springgreen",
    "DQN+LTA+Reward": "C7",

    "DQN+LTA eta=0.2": "C1",
    "DQN+LTA eta=0.4": "C2",
    "DQN+LTA eta=0.6": "C3",
    "DQN+LTA eta=0.8": "C4",

    "Laplace": "gray",
    "Scratch DQN": "black",
    "Random": "navy",
    "Input": "gold",
}

mc_learn_sweep = [
    {"label": "DQN",
     "control": "data/output/test/mountaincar/representations/dqn/sweep/",
     },
    {"label": "DQN+LTA",
     "control": "data/output/test/mountaincar/representations/dqn_lta/sweep/",
     },
    {"label": "DQN+LTA(no target)",
     "control": "data/output/test/mountaincar/representations/dqn_lta/no_target/",
     },
]

# gh_learn_sweep = [
#     {"label": "DQN",
#      "control": "data/output/test/gridhard/representations/dqn/sweep/",
#      },
#     {"label": "DQN+LTA",
#      "control": "data/output/test/gridhard/representations/dqn_lta/sweep/",
#      },
# ]
# gh_learn = [
#     {"label": "DQN", "property": "data/output/test/",
#      "control": "data/output/test/gridhard/representations/dqn/best/",
#     },
#     {"label": "DQN+LTA", "property": "data/output/test/",
#      "control": "data/output/test/gridhard/representations/dqn_lta/best/",
#     },
# ]

gh_same_sweep = [
    {"label": "DQN",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn/sweep/",
     },
    {"label": "DQN+Control1g",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_aux/aux_control/sweep_1g/",
     },
    {"label": "DQN+Control5g",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_aux/aux_control/sweep_5g/",
     },
    {"label": "DQN+XY",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_aux/info/sweep/",
     },
    {"label": "DQN+Decoder",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_aux/input_decoder/sweep/",
     },
    {"label": "DQN+NAS",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_aux/nas_v2_delta/sweep/",
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_aux/reward/sweep/",
     },
    {"label": "DQN+SF",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_aux/successor_as/sweep/",
     },
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta/eta_study_0.2_sweep/",
     },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta/eta_study_0.4_sweep/",
     },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta/eta_study_0.6_sweep/",
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta/eta_study_0.8_sweep/",
     },
    {"label": "DQN+LTA+Control1g",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta_aux/aux_control/sweep_1g/",
     },
    {"label": "DQN+LTA+Control5g",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta_aux/aux_control/sweep_5g/",
     },
    {"label": "DQN+LTA+XY",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta_aux/info/sweep/",
     },
    {"label": "DQN+LTA+Decoder",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta_aux/input_decoder/sweep/",
     },
    {"label": "DQN+LTA+NAS",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta_aux/nas_v2_delta/sweep/",
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta_aux/reward/sweep/",
     },
    {"label": "DQN+LTA+SF",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta_aux/successor_as/sweep/",
     },
    {"label": "Random",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/random/sweep/",
     },
    {"label": "Input",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/input/sweep/",
     },
]
gh_same = [
    {"label": "DQN", "property": "data/output/test/",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn/best/"
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_aux/reward/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_aux/reward/best/"
     },
    {"label": "DQN+LTA", "property": "data/output/test/",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/best/"
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/dqn_lta_aux/reward/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta_aux/reward/best/"
     },
    {"label": "Random",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/random/best/",
     "property": "data/output/test/gridhard/property/random/best",
     },
    {"label": "Input",
     "control": "data/output/test/gridhard/control/same_task/fix_rep/input/best/",
     "property": "data/output/test/gridhard/property/input/best",
     },
]

gh_similar_sweep = [
    {"label": "DQN",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn/sweep/",
     },
    {"label": "DQN+Control1g",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_aux/aux_control/sweep_1g/",
     },
    {"label": "DQN+Control5g",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_aux/aux_control/sweep_5g/",
     },
    {"label": "DQN+XY",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_aux/info/sweep/",
     },
    {"label": "DQN+Decoder",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_aux/input_decoder/sweep/",
     },
    {"label": "DQN+NAS",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_aux/nas_v2_delta/sweep/",
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_aux/reward/sweep/",
     },
    {"label": "DQN+SF",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_aux/successor_as/sweep/",
     },
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta/eta_study_0.2_sweep/",
     },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta/eta_study_0.4_sweep/",
     },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta/eta_study_0.6_sweep/",
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta/eta_study_0.8_sweep/",
     },
    {"label": "DQN+LTA+Control1g",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta_aux/aux_control/sweep_1g/",
     },
    {"label": "DQN+LTA+Control5g",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta_aux/aux_control/sweep_5g/",
     },
    {"label": "DQN+LTA+XY",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta_aux/info/sweep/",
     },
    {"label": "DQN+LTA+Decoder",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta_aux/input_decoder/sweep/",
     },
    {"label": "DQN+LTA+NAS",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta_aux/nas_v2_delta/sweep/",
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta_aux/reward/sweep/",
     },
    {"label": "DQN+LTA+SF",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta_aux/successor_as/sweep/",
     },
    {"label": "Random",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/random/sweep/",
     },
    {"label": "Input",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/input/sweep/",
     },
]
gh_similar = [
    {"label": "DQN", "property": "data/output/test/",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn/best/"
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_aux/reward/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_aux/reward/best/"
     },
    {"label": "DQN+LTA", "property": "data/output/test/",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/best/"
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/dqn_lta_aux/reward/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta_aux/reward/best/"
     },
    {"label": "Random",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/random/best/",
     "property": "data/output/test/gridhard/property/random/best",
     },
    {"label": "Input",
     "control": "data/output/test/gridhard/control/similar_task/fix_rep/input/best/",
     "property": "data/output/test/gridhard/property/input/best",
     },
]

gh_diff_sweep = [
    {"label": "DQN",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn/sweep/",
     },
    {"label": "DQN+Control1g",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_aux/aux_control/sweep_1g/",
     },
    {"label": "DQN+Control5g",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_aux/aux_control/sweep_5g/",
     },
    {"label": "DQN+XY",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_aux/info/sweep/",
     },
    {"label": "DQN+Decoder",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_aux/input_decoder/sweep/",
     },
    {"label": "DQN+NAS",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_aux/nas_v2_delta/sweep/",
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_aux/reward/sweep/",
     },
    {"label": "DQN+SF",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_aux/successor_as/sweep/",
     },
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.2_sweep/",
     },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.4_sweep/",
     },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.6_sweep/",
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.8_sweep/",
     },
    {"label": "DQN+LTA+Control1g",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta_aux/aux_control/sweep_1g/",
     },
    {"label": "DQN+LTA+Control5g",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta_aux/aux_control/sweep_5g/",
     },
    {"label": "DQN+LTA+XY",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta_aux/info/sweep/",
     },
    {"label": "DQN+LTA+Decoder",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta_aux/input_decoder/sweep/",
     },
    {"label": "DQN+LTA+NAS",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta_aux/nas_v2_delta/sweep/",
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta_aux/reward/sweep/",
     },
    {"label": "DQN+LTA+SF",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta_aux/successor_as/sweep/",
     },
    {"label": "Random",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/random/sweep/",
     },
    {"label": "Input",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/input/sweep/",
     },
]
gh_diff = [
    {"label": "DQN", "property": "data/output/test/",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn/best/"
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_aux/reward/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_aux/reward/best/"
     },
    {"label": "DQN+LTA", "property": "data/output/test/",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/best/"
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta_aux/reward/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta_aux/reward/best/"
     },
    {"label": "Random",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/random/best/",
     "property": "data/output/test/gridhard/property/random/best",
     },
    {"label": "Input",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/input/best/",
     "property": "data/output/test/gridhard/property/input/best",
     },

    # {"label": "DQN+LTA eta=0.2",
    #  "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.2_best/",
    #  "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.2_best/"
    #  },
    # {"label": "DQN+LTA eta=0.6",
    #  "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.6_best/",
    #  "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.6_best/"
    #  },
    # {"label": "DQN+LTA eta=0.8",
    #  "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.8_best/",
    #  "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.8_best/"
    #  }
]

gh_diff_tune_sweep = [
    {"label": "DQN",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn/sweep/",
     },
    {"label": "DQN+Control1g",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_aux/aux_control/sweep_1g/",
     },
    {"label": "DQN+Control5g",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_aux/aux_control/sweep_5g/",
     },
    {"label": "DQN+XY",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_aux/info/sweep/",
     },
    {"label": "DQN+Decoder",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_aux/input_decoder/sweep/",
     },
    {"label": "DQN+NAS",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_aux/nas_v2_delta/sweep/",
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_aux/reward/sweep/",
     },
    {"label": "DQN+SF",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_aux/successor_as/sweep/",
     },
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.2_sweep/",
     },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.4_sweep/",
     },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.6_sweep/",
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.8_sweep/",
     },
    {"label": "DQN+LTA+Control1g",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta_aux/aux_control/sweep_1g/",
     },
    {"label": "DQN+LTA+Control5g",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta_aux/aux_control/sweep_5g/",
     },
    {"label": "DQN+LTA+XY",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta_aux/info/sweep/",
     },
    {"label": "DQN+LTA+Decoder",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta_aux/input_decoder/sweep/",
     },
    {"label": "DQN+LTA+NAS",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta_aux/nas_v2_delta/sweep/",
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta_aux/reward/sweep/",
     },
    {"label": "DQN+LTA+SF",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta_aux/successor_as/sweep/",
     },
    {"label": "Random",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/random/sweep/",
     },
    {"label": "Input",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/input/sweep/",
     },
]
gh_diff_tune = [
    {"label": "DQN", "property": "data/output/test/",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn/best/"
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_aux/reward/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_aux/reward/best/"
     },
    {"label": "DQN+LTA", "property": "data/output/test/",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/best/"
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta_aux/reward/best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta_aux/reward/best/"
     },
    {"label": "Random",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/random/best/",
     "property": "data/output/test/gridhard/property/random/best",
     },
    #
    # {"label": "DQN+LTA eta=0.2",
    #  "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.2_best/",
    #  "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.2_best/"
    #  },
    # {"label": "DQN+LTA eta=0.6",
    #  "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.6_best/",
    #  "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.6_best/"
    #  },
    # {"label": "DQN+LTA eta=0.8",
    #  "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.8_best/",
    #  "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.8_best/"
    #  }
]

gh_etaStudy_diff_fix_sweep = [
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.2/",
    },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.4/",
    },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.6/",
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.8/",
     },
]
gh_etaStudy_diff_tune_sweep = [
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.2/",
     },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.4/",
    },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.6/",
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.8/",
     },
]
gh_etaStudy_diff_fix = [
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.2_best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.2_best/"
     },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.4_best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.4_best/"
     },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.6_best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.6_best/"
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/control/different_task/fix_rep/dqn_lta/eta_study_0.8_best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.8_best/"
     },
]
gh_etaStudy_diff_tune = [
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.2_best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.2_best/"
     },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.4_best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.4_best/"
    },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.6_best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.6_best/"
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/control/different_task/fine_tune/dqn_lta/eta_study_0.8_best/",
     "online_measure": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.8_best/"
     },
]


gh_online_sweep = [
    {"label": "DQN",
     "control": "data/output/test/gridhard/online_property/dqn/sweep/",
     },
    {"label": "DQN+Control1g",
     "control": "data/output/test/gridhard/online_property/dqn_aux/freq8/aux_control/sweep_1g/",
     # "control": "data/output/test/gridhard/online_property/dqn_aux/freq64/aux_control/sweep_1g/",
     },
    {"label": "DQN+Control1g",
     "control": "data/output/test/gridhard/online_property/dqn_aux/freq8/aux_control/sweep_5g/",
     # "control": "data/output/test/gridhard/online_property/dqn_aux/freq64/aux_control/sweep_5g/",
     },
    {"label": "DQN+XY",
     "control": "data/output/test/gridhard/online_property/dqn_aux/freq8/info/sweep/",
     # "control": "data/output/test/gridhard/online_property/dqn_aux/freq64/info/sweep/",
     },
    {"label": "DQN+Decoder",
     "control": "data/output/test/gridhard/online_property/dqn_aux/freq8/input_decoder/sweep/",
     # "control": "data/output/test/gridhard/online_property/dqn_aux/freq64/input_decoder/sweep/",
     },
    {"label": "DQN+NAS",
     "control": "data/output/test/gridhard/online_property/dqn_aux/freq8/nas_v2_delta/sweep/",
     # "control": "data/output/test/gridhard/online_property/dqn_aux/freq64/nas_v2_delta/sweep/",
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/online_property/dqn_aux/freq8/reward/sweep/",
     # "control": "data/output/test/gridhard/online_property/dqn_aux/freq64/reward/sweep/",
     },
    {"label": "DQN+SF",
     "control": "data/output/test/gridhard/online_property/dqn_aux/freq8/successor_as/sweep/",
     # "control": "data/output/test/gridhard/online_property/dqn_aux/freq64/successor_as/sweep/",
     },
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.2_sweep/",
     },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.4_sweep/",
     },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.6_sweep/",
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.8_sweep/",
     },
    {"label": "DQN+LTA+Control1g",
     "control": "data/output/test/gridhard/online_property/dqn_lta_aux/aux_control/sweep_1g/",
     },
    {"label": "DQN+LTA+Control5g",
     "control": "data/output/test/gridhard/online_property/dqn_lta_aux/aux_control/sweep_5g/",
     },
    {"label": "DQN+LTA+XY",
     "control": "data/output/test/gridhard/online_property/dqn_lta_aux/info/sweep/",
     },
    {"label": "DQN+LTA+Decoder",
     "control": "data/output/test/gridhard/online_property/dqn_lta_aux/input_decoder/sweep/",
     },
    {"label": "DQN+LTA+NAS",
     "control": "data/output/test/gridhard/online_property/dqn_lta_aux/nas_v2_delta/sweep/",
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/online_property/dqn_lta_aux/reward/sweep/",
     },
    {"label": "DQN+LTA+SF",
     "control": "data/output/test/gridhard/online_property/dqn_lta_aux/successor_as/sweep/",
     }
]

gh_online = [
    {"label": "DQN",
     "control": "data/output/test/gridhard/online_property/dqn/best/",
     },
    {"label": "DQN+LTA",
     "control": "data/output/test/gridhard/online_property/dqn_lta/best/",
     },
    {"label": "DQN+Reward",
     "control": "data/output/test/gridhard/online_property/dqn_aux/reward/best/",
     },
    {"label": "DQN+LTA+Reward",
     "control": "data/output/test/gridhard/online_property/dqn_lta_aux/reward/best/",
     },
]

gh_etaStudy_online = [
    {"label": "DQN+LTA eta=0.2",
     "control": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.2_best/",
     },
    {"label": "DQN+LTA eta=0.4",
     "control": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.4_best/",
     },
    {"label": "DQN+LTA eta=0.6",
     "control": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.6_best/",
     },
    {"label": "DQN+LTA eta=0.8",
     "control": "data/output/test/gridhard/online_property/dqn_lta/eta_study_0.8_best/",
     },
]


# ------------------------- Picky Eater Environment --------------------

dqn_lta_learn_sweep = [
    {"label": "DQN+LTA",
     "control": "data/output/test/picky_eater/online_property/dqn_lta/sweep",
     },
    ]

dqn_lta_1_learn_sweep = [
    {"label": "DQN+LTA+1",
     "control": "data/output/test/picky_eater/online_property/dqn_lta_1/sweep",
     },
    ]


dqn_learn_sweep = [
    {"label": "DQN",
     "control": "data/output/test/picky_eater/online_property/dqn/sweep",
     },
    ]
