target_keywords = {
    "decorrelation.txt": "Decorrelation:",
    "distance.txt": "Distance",
    "interference.txt": "Interference:",
    "linear_probing_xy.txt": "Percentage error",
    "linear_probing_color.txt": "Percentage error",
    "linear_probing_count.txt": "Percentage error",
    "orthogonality.txt": "Orthogonality:",
    "sparsity_instance.txt": "sparsity:",
}

violin_colors = {
    "DQN": "C4",

    "DQN+XY": "C1",
    "DQN+XY+color": "goldenrod",
    "DQN+XY+count": "C8",
    "DQN+Decoder": "C3",
    "DQN+NAS": "C5",
    "DQN+SF": "C6",
    "DQN+AuxControl": "C0",
    "DQN+AuxControl1g": "C0",
    "DQN+AuxControl5g": "C9",

    "Sparse0.1": "C2",
    "Sparse0.2": "springgreen",
    "Sparse0.4": "lightgreen",

    "Laplace": "gray",
    "Scratch DQN": "black",
    "Random": "navy",
    "Input": "gold",
}

maze_learn = [
    {"label": "DQN", "property": "data/output/paper_v2/gridhard/property/dqn/best/",
     "control": "data/output/paper_v2/gridhard/representations/dqn/best/",
     "optimal": 1},
    {"label": "DQN+AuxControl1g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_1g/",
     "control": "data/output/paper_v2/gridhard/representations/dqn_aux/aux_control/best_1g/",
     "optimal": 1},
    {"label": "DQN+AuxControl5g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_5g/",
     "control": "data/output/paper_v2/gridhard/representations/dqn_aux/aux_control/best_5g/",
     "optimal": 1},
    {"label": "DQN+XY", "property": "data/output/paper_v2/gridhard/property/dqn_aux/info/best/",
     "control": "data/output/paper_v2/gridhard/representations/dqn_aux/info/best/",
     "optimal": 1},
    {"label": "DQN+Decoder", "property": "data/output/paper_v2/gridhard/property/dqn_aux/input_decoder/best/",
     "control": "data/output/paper_v2/gridhard/representations/dqn_aux/input_decoder/best/",
     "optimal": 1},
    {"label": "DQN+NAS", "property": "data/output/paper_v2/gridhard/property/dqn_aux/nas_v2_delta/best/",
     "control": "data/output/paper_v2/gridhard/representations/dqn_aux/nas_v2_delta/best/",
     "optimal": 1},
    {"label": "DQN+SF", "property": "data/output/paper_v2/gridhard/property/dqn_aux/successor_as/best/",
     "control": "data/output/paper_v2/gridhard/representations/dqn_aux/successor_as/best/",
     "optimal": 1},
    {"label": "Sparse0.1", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.1/best/",
     "control": "data/output/paper_v2/gridhard/representations/dqn_sparse_highdim/sparse0.1/best/",
     "optimal": 1},
    {"label": "Sparse0.2", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.2/best/",
     "control": "data/output/paper_v2/gridhard/representations/dqn_sparse_highdim/sparse0.2/best/",
     "optimal": 1},
    {"label": "Sparse0.4", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.4/best/",
     "control": "data/output/paper_v2/gridhard/representations/dqn_sparse_highdim/sparse0.4/best/",
     "optimal": 1},
]

maze_same = [
    {"label": "DQN", "property": "data/output/paper_v2/gridhard/property/dqn/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn/best/",
     "optimal": 1},
    {"label": "DQN+AuxControl1g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_1g/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn_aux/aux_control/best_1g/",
     "optimal": 1},
    {"label": "DQN+AuxControl5g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_5g/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn_aux/aux_control/best_5g/",
     "optimal": 1},
    {"label": "DQN+XY", "property": "data/output/paper_v2/gridhard/property/dqn_aux/info/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn_aux/info/best/",
     "optimal": 1},
    {"label": "DQN+Decoder", "property": "data/output/paper_v2/gridhard/property/dqn_aux/input_decoder/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn_aux/input_decoder/best/",
     "optimal": 1},
    {"label": "DQN+NAS", "property": "data/output/paper_v2/gridhard/property/dqn_aux/nas_v2_delta/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn_aux/nas_v2_delta/best/",
     "optimal": 1},
    {"label": "DQN+SF", "property": "data/output/paper_v2/gridhard/property/dqn_aux/successor_as/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn_aux/successor_as/best/",
     "optimal": 1},
    {"label": "Sparse0.1", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.1/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn_sparse_highdim/sparse0.1/best/",
     "optimal": 1},
    {"label": "Sparse0.2", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.2/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn_sparse_highdim/sparse0.2/best/",
     "optimal": 1},
    {"label": "Sparse0.4", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.4/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/dqn_sparse_highdim/sparse0.4/best/",
     "optimal": 1},
    {"label": "Random", "property": "data/output/paper_v2/gridhard/property/random/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/random/best/",
     "optimal": 1},
    {"label": "Input", "property": "data/output/paper_v2/gridhard/property/input/best/",
     "control": "data/output/paper_v2/gridhard/control/same_task/fix_rep/input/best/",
     "optimal": 1},
]

maze_similar = [
    {"label": "DQN", "property": "data/output/paper_v2/gridhard/property/dqn/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn/best/",
     "optimal": 1},
    {"label": "DQN+AuxControl1g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_1g/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn_aux/aux_control/best_1g/",
     "optimal": 1},
    {"label": "DQN+AuxControl5g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_5g/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn_aux/aux_control/best_5g/",
     "optimal": 1},
    {"label": "DQN+XY", "property": "data/output/paper_v2/gridhard/property/dqn_aux/info/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn_aux/info/best/",
     "optimal": 1},
    {"label": "DQN+Decoder", "property": "data/output/paper_v2/gridhard/property/dqn_aux/input_decoder/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn_aux/input_decoder/best/",
     "optimal": 1},
    {"label": "DQN+NAS", "property": "data/output/paper_v2/gridhard/property/dqn_aux/nas_v2_delta/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn_aux/nas_v2_delta/best/",
     "optimal": 1},
    {"label": "DQN+SF", "property": "data/output/paper_v2/gridhard/property/dqn_aux/successor_as/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn_aux/successor_as/best/",
     "optimal": 1},
    {"label": "Sparse0.1", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.1/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn_sparse_highdim/sparse0.1/best/",
     "optimal": 1},
    {"label": "Sparse0.2", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.2/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn_sparse_highdim/sparse0.2/best/",
     "optimal": 1},
    {"label": "Sparse0.4", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.4/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/dqn_sparse_highdim/sparse0.4/best/",
     "optimal": 1},
    {"label": "Random", "property": "data/output/paper_v2/gridhard/property/random/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/random/best/",
     "optimal": 1},
    {"label": "Input", "property": "data/output/paper_v2/gridhard/property/input/best/",
     "control": "data/output/paper_v2/gridhard/control/similar_task/fix_rep/input/best/",
     "optimal": 1},
]

maze_different_fix = [
    {"label": "DQN", "property": "data/output/paper_v2/gridhard/property/dqn/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn/best/",
     "optimal": 1},
    {"label": "DQN+AuxControl1g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_1g/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn_aux/aux_control/best_1g/",
     "optimal": 1},
    {"label": "DQN+AuxControl5g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_5g/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn_aux/aux_control/best_5g/",
     "optimal": 1},
    {"label": "DQN+XY", "property": "data/output/paper_v2/gridhard/property/dqn_aux/info/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn_aux/info/best/",
     "optimal": 1},
    {"label": "DQN+Decoder", "property": "data/output/paper_v2/gridhard/property/dqn_aux/input_decoder/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn_aux/input_decoder/best/",
     "optimal": 1},
    {"label": "DQN+NAS", "property": "data/output/paper_v2/gridhard/property/dqn_aux/nas_v2_delta/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn_aux/nas_v2_delta/best/",
     "optimal": 1},
    {"label": "DQN+SF", "property": "data/output/paper_v2/gridhard/property/dqn_aux/successor_as/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn_aux/successor_as/best/",
     "optimal": 1},
    {"label": "Sparse0.1", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.1/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn_sparse_highdim/sparse0.1/best/",
     "optimal": 1},
    {"label": "Sparse0.2", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.2/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn_sparse_highdim/sparse0.2/best/",
     "optimal": 1},
    {"label": "Sparse0.4", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.4/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/dqn_sparse_highdim/sparse0.4/best/",
     "optimal": 1},
    {"label": "Random", "property": "data/output/paper_v2/gridhard/property/random/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/random/best/",
     "optimal": 1},
    {"label": "Input", "property": "data/output/paper_v2/gridhard/property/input/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fix_rep/input/best/",
     "optimal": 1},
]

maze_different_tune = [
    {"label": "DQN", "property": "data/output/paper_v2/gridhard/property/dqn/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn/best/",
     "optimal": 1},
    {"label": "DQN+AuxControl1g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_1g/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn_aux/aux_control/best_1g/",
     "optimal": 1},
    {"label": "DQN+AuxControl5g", "property": "data/output/paper_v2/gridhard/property/dqn_aux/aux_control/best_5g/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn_aux/aux_control/best_5g/",
     "optimal": 1},
    {"label": "DQN+XY", "property": "data/output/paper_v2/gridhard/property/dqn_aux/info/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn_aux/info/best/",
     "optimal": 1},
    {"label": "DQN+Decoder", "property": "data/output/paper_v2/gridhard/property/dqn_aux/input_decoder/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn_aux/input_decoder/best/",
     "optimal": 1},
    {"label": "DQN+NAS", "property": "data/output/paper_v2/gridhard/property/dqn_aux/nas_v2_delta/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn_aux/nas_v2_delta/best/",
     "optimal": 1},
    {"label": "DQN+SF", "property": "data/output/paper_v2/gridhard/property/dqn_aux/successor_as/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn_aux/successor_as/best/",
     "optimal": 1},
    {"label": "Sparse0.1", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.1/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn_sparse_highdim/sparse0.1/best/",
     "optimal": 1},
    {"label": "Sparse0.2", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.2/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn_sparse_highdim/sparse0.2/best/",
     "optimal": 1},
    {"label": "Sparse0.4", "property": "data/output/paper_v2/gridhard/property/dqn_sparse_highdim/sparse0.4/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/dqn_sparse_highdim/sparse0.4/best/",
     "optimal": 1},
    {"label": "Random", "property": "data/output/paper_v2/gridhard/property/random/best/",
     "control": "data/output/paper_v2/gridhard/control/different_task/fine_tune/random/best/",
     "optimal": 1},
]

# mazexy_same = [
#     {"label": "DQN", "property": "data/output/linear_vf/gridhard_xy/property/dqn/best/",
#      "control": ""},
#     {"label": "Sparse", "property": "data/output/linear_vf/gridhard_xy/property/dqn_sparse/best/",
#      "control": ""},
# ]

eater_learn = [
    {"label": "DQN", "property": "data/output/paper_v2/collect_two/property/dqn/best/",
     "control": "data/output/paper_v2/collect_two/representations/dqn/best/",
     "optimal": 5.5},
    {"label": "DQN+AuxControl", "property": "data/output/paper_v2/collect_two/property/dqn_aux/aux_control/best/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_aux/aux_control/best/",
     "optimal": 5.5},
    {"label": "DQN+XY", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_aux/info/best_xy/",
     "optimal": 5.5},
    {"label": "DQN+XY+color", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy+color/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_aux/info/best_xy+color/",
     "optimal": 5.5},
    {"label": "DQN+XY+count", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy+count/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_aux/info/best_xy+count/",
     "optimal": 5.5},
    {"label": "DQN+Decoder", "property": "data/output/paper_v2/collect_two/property/dqn_aux/input_decoder/best/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_aux/input_decoder/best/",
     "optimal": 5.5},
    {"label": "DQN+NAS", "property": "data/output/paper_v2/collect_two/property/dqn_aux/nas_v2_delta/best/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_aux/nas_v2_delta/best/",
     "optimal": 5.5},
    {"label": "DQN+SF", "property": "data/output/paper_v2/collect_two/property/dqn_aux/successor_as/best/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_aux/successor_as/best/",
     "optimal": 5.5},
    {"label": "Sparse0.1", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.1/best/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_sparse_highdim/sparse0.1/best/",
     "optimal": 5.5},
    {"label": "Sparse0.2", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.2/best/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_sparse_highdim/sparse0.2/best/",
     "optimal": 5.5},
    {"label": "Sparse0.4", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.4/best/",
     "control": "data/output/paper_v2/collect_two/representations/dqn_sparse_highdim/sparse0.4/best/",
     "optimal": 5.5},
]

eater_same = [
    {"label": "DQN", "property": "data/output/paper_v2/collect_two/property/dqn/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn/best/",
     "optimal": 5.5},
    {"label": "DQN+AuxControl", "property": "data/output/paper_v2/collect_two/property/dqn_aux/aux_control/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_aux/aux_control/best/",
     "optimal": 5.5},
    {"label": "DQN+XY", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_aux/info/best_xy/",
     "optimal": 5.5},
    {"label": "DQN+XY+color", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy+color/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_aux/info/best_xy+color/",
     "optimal": 5.5},
    {"label": "DQN+XY+count", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy+count/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_aux/info/best_xy+count/",
     "optimal": 5.5},
    {"label": "DQN+Decoder", "property": "data/output/paper_v2/collect_two/property/dqn_aux/input_decoder/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_aux/input_decoder/best/",
     "optimal": 5.5},
    {"label": "DQN+NAS", "property": "data/output/paper_v2/collect_two/property/dqn_aux/nas_v2_delta/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_aux/nas_v2_delta/best/",
     "optimal": 5.5},
    {"label": "DQN+SF", "property": "data/output/paper_v2/collect_two/property/dqn_aux/successor_as/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_aux/successor_as/best/",
     "optimal": 5.5},
    {"label": "Sparse0.1", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.1/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_sparse_highdim/sparse0.1/best/",
     "optimal": 5.5},
    {"label": "Sparse0.2", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.2/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_sparse_highdim/sparse0.2/best/",
     "optimal": 5.5},
    {"label": "Sparse0.4", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.4/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/dqn_sparse_highdim/sparse0.4/best/",
     "optimal": 5.5},
    {"label": "Random", "property": "data/output/paper_v2/collect_two/property/random/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/random/best/",
     "optimal": 5.5},
    {"label": "Input", "property": "data/output/paper_v2/collect_two/property/input/best/",
     "control": "data/output/paper_v2/collect_two/control/same_task/fix_rep/input/best/",
     "optimal": 5.5},
]

eater_different_fix = [
    {"label": "DQN", "property": "data/output/paper_v2/collect_two/property/dqn/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn/best/",
     "optimal": 5.5},
    {"label": "DQN+AuxControl", "property": "data/output/paper_v2/collect_two/property/dqn_aux/aux_control/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_aux/aux_control/best/",
     "optimal": 5.5},
    {"label": "DQN+XY", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_aux/info/best_xy/",
     "optimal": 5.5},
    {"label": "DQN+XY+color", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy+color/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_aux/info/best_xy+color/",
     "optimal": 5.5},
    {"label": "DQN+XY+count", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy+count/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_aux/info/best_xy+count/",
     "optimal": 5.5},
    {"label": "DQN+Decoder", "property": "data/output/paper_v2/collect_two/property/dqn_aux/input_decoder/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_aux/input_decoder/best/",
     "optimal": 5.5},
    {"label": "DQN+NAS", "property": "data/output/paper_v2/collect_two/property/dqn_aux/nas_v2_delta/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_aux/nas_v2_delta/best/",
     "optimal": 5.5},
    {"label": "DQN+SF", "property": "data/output/paper_v2/collect_two/property/dqn_aux/successor_as/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_aux/successor_as/best/",
     "optimal": 5.5},
    {"label": "Sparse0.1", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.1/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_sparse_highdim/sparse0.1/best/",
     "optimal": 5.5},
    {"label": "Sparse0.2", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.2/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_sparse_highdim/sparse0.2/best/",
     "optimal": 5.5},
    {"label": "Sparse0.4", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.4/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/dqn_sparse_highdim/sparse0.4/best/",
     "optimal": 5.5},
    {"label": "Random", "property": "data/output/paper_v2/collect_two/property/random/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/random/best/",
     "optimal": 5.5},
    {"label": "Input", "property": "data/output/paper_v2/collect_two/property/input/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/input/best/",
     "optimal": 5.5},
]

eater_different_tune = [
    {"label": "DQN", "property": "data/output/paper_v2/collect_two/property/dqn/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn/best/",
     "optimal": 5.5},
    {"label": "DQN+AuxControl", "property": "data/output/paper_v2/collect_two/property/dqn_aux/aux_control/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_aux/aux_control/best/",
     "optimal": 5.5},
    {"label": "DQN+XY", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_aux/info/best_xy/",
     "optimal": 5.5},
    {"label": "DQN+XY+color", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy+color/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_aux/info/best_xy+color/",
     "optimal": 5.5},
    {"label": "DQN+XY+count", "property": "data/output/paper_v2/collect_two/property/dqn_aux/info/best_xy+count/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_aux/info/best_xy+count/",
     "optimal": 5.5},
    {"label": "DQN+Decoder", "property": "data/output/paper_v2/collect_two/property/dqn_aux/input_decoder/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_aux/input_decoder/best/",
     "optimal": 5.5},
    {"label": "DQN+NAS", "property": "data/output/paper_v2/collect_two/property/dqn_aux/nas_v2_delta/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_aux/nas_v2_delta/best/",
     "optimal": 5.5},
    {"label": "DQN+SF", "property": "data/output/paper_v2/collect_two/property/dqn_aux/successor_as/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_aux/successor_as/best/",
     "optimal": 5.5},
    {"label": "Sparse0.1", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.1/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_sparse_highdim/sparse0.1/best/",
     "optimal": 5.5},
    {"label": "Sparse0.2", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.2/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_sparse_highdim/sparse0.2/best/",
     "optimal": 5.5},
    {"label": "Sparse0.4", "property": "data/output/paper_v2/collect_two/property/dqn_sparse_highdim/sparse0.4/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/dqn_sparse_highdim/sparse0.4/best/",
     "optimal": 5.5},
    {"label": "Random", "property": "data/output/paper_v2/collect_two/property/random/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fine_tune/random/best/",
     "optimal": 5.5},
    {"label": "Input", "property": "data/output/paper_v2/collect_two/property/input/best/",
     "control": "data/output/paper_v2/collect_two/control/different_task/fix_rep/input/best/",
     "optimal": 5.5}, # no fine-tune for input
]
